on: push


jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: dmejiar/git-sync@v1
        with:
          source_repo: "git@github.com:pnnl/PTMPSI.git"
          destination_repo: "git@github.com:pnnl-predictive-phenomics/PTMPSI.git"
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
